server:
  port: "9090"
spring:
  application:
    name: "EtasensAssignment"
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    #    change the db-name
    url: "jdbc:mysql://localhost:3306/assignment"
    #    change the username and password
    username: "root"
    password: "root"
  jpa:
    properties:
      dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
